### PR TITLE
Use reflect.Ptr for go1.17 compatibility

### PR DESCRIPTION
**Pull request by anmaxvl**
Signed-off-by: Maksim An <maksiman@microsoft.com>

### CODE REVIEW

**Comment by anmaxvl** [comment]
@helsaawy @dcantah ptal

**Comment by kevpar** [comment]
Was this a breaking change in `reflect`? Or why is this needed?

**Comment by anmaxvl** [comment]
Go 1.18 introduced `reflect.Pointer` and `reflect.Ptr` is now an alias. The builds break for Go 1.17.x and below.

**Comment by kevpar** [comment]
> Go 1.18 introduced `reflect.Pointer` and `reflect.Ptr` is now an alias. The builds break for Go 1.17.x and below.

Oh, so the code that doesn't work on 1.17 was already checked in, and now we're fixing it.

**Review by kevpar — APPROVED** [review]
LGTM

**Comment by anmaxvl** [comment]
> Oh, so the code that doesn't work on 1.17 was already checked in, and now we're fixing it.

yup!

**Review by dcantah — APPROVED** [review]

**Pull request merged**
